site_name: Blood Donation Campaign Dashboard
site_author: ABO Team
site_description: Documentation for Blood Donation Campaign Analytics Dashboard

repo_url: https://github.com/AlphonseBrandon/blood_donation_campaign_dashboard
site_url: https://AlphonseBrandon.github.io/blood_donation_campaign_dashboard/

docs_dir: docs  # Important: Point to docs subdirectory
site_dir: site

theme:
  name: mkdocs
  palette:
    scheme: default
    primary: red
    accent: red

nav:
  - Home: index.md
  - Getting Started: getting-started.md
  - Technical Documentation:
    - Dashboard: dashboard.md
    - Features: features.md
    - Modeling: modeling.md
    - Eligibility: eligibilty.md
  - About: about.md

plugins:
  - search
  - mkdocstrings:
      default_handler: python
      handlers:
        python:
          paths: [../src]
          options:
            show_source: true
            show_root_heading: true