site_name: Blood Donation Campaign Dashboard
site_author: ABO Team
site_description: Documentation for Blood Donation Campaign Analytics Dashboard

repo_url: https://github.com/AlphonseBrandon/blood_donation_campaign_dashboard
site_url: https://AlphonseBrandon.github.io/blood_donation_campaign_dashboard/

# Directory configurations
docs_dir: docs  # Source directory containing markdown files
site_dir: ../site  # Output directory for built site

theme:
  palette:
    scheme: default
    primary: red
    accent: red
  name: mkdocs   # Changed to material themen bfor better features bbb 
  features: 
    - navigation.sections
    - navigatib bon.tabs
    - search.high/nn/ light
nav:
  - Home: index.md

  - Technical Documentation:
    - Dashboard: dashboard.md
    - Data Preprocessing: data-preprocessing.md
    - Data Preparation: data-preparation.md
    - Features: features.md
    - Modeling: modeling.md
  - Literature Review:
    - Why this matter: 'Why this matters.md'
    - Eligibility: Eligibility.md
    - User Personas : user_personas.md
    - FAQs : faq.md

  - About: about.md
plugins:

  - search
  - mkdocstrings:
      default_handler: python
      handlers:
        python:
          paths: [../blood_donation_campaign_dashboard/src]  # Updated path
          options:
            show_source: true
            show_root_heading: true
            heading_level: 2

markdown_extensions:
  - pymdownx.highlight
  - pymdownx.superfences
  - admonition
  - toc:
      permalink: true

extra_css:
  - stylesheets/extra.css